apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-website
  namespace: test
spec:
  selector:
    matchLabels:
      app: test-website
  template:
    metadata:
      labels:
        app: test-website
    spec:
      containers:
      - name: website
        image: nfacr.azurecr.io/webdemo/webdemo:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-website
  namespace: test
spec:
  selector:
    app: test-website
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-website
  namespace: test
spec:
  rules:
  - host: test.nillsf.com
    http:    
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-website
            port:
              number: 80