# This is a basic workflow to help you get started with Actions

name: Build-push-deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-push:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: az login
        run: az login --service-principal --username ${{ secrets.APP_ID }} --password ${{ secrets.PASSWORD }} --tenant ${{ secrets.TENANT_ID }} 
        
      - name: Build Docker Container
        run: docker build . -t nfacr.azurecr.io/webdemo/webdemo:${{ github.run_number }}

      - name: ACR login
        run: az acr login -n nfacr

      - name: Push container
        run: docker push nfacr.azurecr.io/webdemo/webdemo:${{ github.run_number }}

  deploy-test:
    runs-on: ubuntu-latest
    environment: 