# This is a basic workflow to help you get started with Actions
name: Build-push-deploy
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-push:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: az login
        run: az login --service-principal --username ${{ secrets.APP_ID }} --password ${{ secrets.PASSWORD }} --tenant ${{ secrets.TENANT_ID }} 
        
      - name: Build Docker Container
        run: docker build . -t nfacr123.azurecr.io/webdemo/webdemo:${{ github.run_number }}

      - name: ACR login
        run: az acr login -n nfacr123

      - name: Push container
        run: docker push nfacr123.azurecr.io/webdemo/webdemo:${{ github.run_number }}

  deploy-test:
    needs: build-push
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2

      - name: az login
        run: az login --service-principal --username ${{ secrets.APP_ID }} --password ${{ secrets.PASSWORD }} --tenant ${{ secrets.TENANT_ID }} 

      - name: get AKS credentials
        run: az aks get-credentials -n nfaks123 -g cdgithubactions        
       # gh-actions

      - name: deploy (will deploy base infra if not exists)
        run: kubectl create -f test.yaml
        continue-on-error: true

      - name: update deployment image
        run: kubectl set image deployment/test-website -n test website=nfacr123.azurecr.io/webdemo/webdemo:${{ github.run_number }}

  deploy-prod:
    needs: deploy-test
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - name: az login
        run: az login --service-principal --username ${{ secrets.APP_ID }} --password ${{ secrets.PASSWORD }} --tenant ${{ secrets.TENANT_ID }} 

      - name: get AKS credentials
        run: az aks get-credentials -n nfaks123 -g gh-actions

      - name: deploy (will deploy base infra if not exists)
        run: kubectl create -f prod.yaml
        continue-on-error: true
      - name: update deployment image
        run: kubectl set image deployment/prod-website -n prod website=nfacr123.azurecr.io/webdemo/webdemo:${{ github.run_number }}
